//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionStateSql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SessionStateSql.SQLScripts", typeof(SQLScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO
        ///DROP PROCEDURE [dbo].[DeleteExpiredSessions]
        ///GO
        ///DROP PROCEDURE [dbo].[GetHashCode]
        ///GO
        ///DROP PROCEDURE [dbo].[GetMajorVersion]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetAppID]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItem]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItem2]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItem3]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItemExclusive]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItemExclusive2]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetStateItemExclusive3]
        ///GO
        ///DROP PROCEDURE [dbo].[TempGetVer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SessionStateDown {
            get {
                return ResourceManager.GetString("SessionStateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE dbo.GetMajorVersion
        ///	@@ver int OUTPUT
        ///AS
        ///BEGIN
        ///	DECLARE @version		nchar(100)
        ///	DECLARE @dot			int
        ///	DECLARE @hyphen		 int
        ///	DECLARE @SqlToExec	 nchar(4000)
        ///
        ///	SELECT @@ver = 7
        ///	SELECT @version = @@Version
        ///	SELECT @hyphen = CHARINDEX(N&apos; - &apos;, @version)
        ///	IF (NOT(@hyphen IS NULL) AND @hyphen &gt; 0)
        ///	BEGIN
        ///		SELECT @hyphen = @hyphen + 3
        ///		SELECT @dot	= CHARINDEX(N&apos;.&apos;, @version, @hyphen)
        ///		IF (NOT(@dot IS NULL) AND @dot &gt; @hyphen)
        ///		BEGIN
        ///			SELECT @version = SUBSTRING(@version, @hyph [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SessionStateUp {
            get {
                return ResourceManager.GetString("SessionStateUp", resourceCulture);
            }
        }
    }
}
